const productosData = [
    /* Moda */
    {
        categoria: "Moda",
        titulo: "Camiseta Oversize",
        precio: 12000,
        info: "Camiseta cómoda y moderna",
        tamano: "S, M, L, XL",
        colores: "Negro, Blanco, Azul",
        marca: "UrbanStyle",
        tienda: "Moda CR",
        stock: 15,
        fecha: "06-04-2026",
        valoracion: 4,
        imagen: "/img/Catalogo/camisa.jpg"
    },
    {
        categoria: "Moda",
        titulo: "Pantalón Jogger",
        precio: 14000,
        info: "Pantalón cómodo estilo urbano",
        tamano: "S, M, L, XL",
        colores: "Negro, Gris",
        marca: "UrbanStyle",
        tienda: "Moda CR",
        stock: 12,
        fecha: "04-01-2026",
        valoracion: 4,
        imagen: "/img/Catalogo/pantalon.jpg"
    },
    {
        categoria: "Moda",
        titulo: "Chaqueta Denim",
        precio: 18000,
        info: "Chaqueta clásica de mezclilla resistente y cómoda",
        tamano: "S, M, L",
        colores: "Azul, Negro",
        marca: "StreetWear",
        tienda: "Estilo CR",
        stock: 10,
        fecha: "20-03-2026",
        valoracion: 5,
        imagen: "/img/Catalogo/chaqueta.jpg"
    },
    {
        categoria: "Moda",
        titulo: "Sudadera Hoodie",
        precio: 20000,
        info: "Sudadera con capucha abrigada",
        tamano: "M, L, XL",
        colores: "Negro, Blanco",
        marca: "StreetWear",
        tienda: "Estilo CR",
        stock: 9,
        fecha: "04-03-2026",
        valoracion: 5,
        imagen: "/img/Catalogo/sudadera.jpg"
    },
    /* Calzado */
    {
        categoria: "Calzado",
        titulo: "Zapatillas Running",
        precio: 25000,
        info: "Zapatillas ligeras ideales para correr",
        tamano: "38-44",
        colores: "Negro, Blanco",
        marca: "RunFast",
        tienda: "Deportes CR",
        stock: 20,
        fecha: "15-02-2026",
        valoracion: 4,
        imagen: "/img/Catalogo/zapatilla.jpg"
    },
    {
        categoria: "Calzado",
        titulo: "Tenis Casual",
        precio: 21000,
        info: "Tenis cómodos para uso diario",
        tamano: "38-44",
        colores: "Blanco, Azul",
        marca: "RunFast",
        tienda: "Deportes CR",
        stock: 17,
        fecha: "28-03-2026",
        valoracion: 4,
        imagen: "/img/Catalogo/Tenis.jpg"
    },
    {
        categoria: "Calzado",
        titulo: "Botas Urbanas",
        precio: 32000,
        info: "Botas resistentes para uso diario",
        tamano: "39-45",
        colores: "Marrón, Negro",
        marca: "UrbanStep",
        tienda: "Zapatos CR",
        stock: 8,
        fecha: "10-01-2026",
        valoracion: 5,
        imagen: "/img/Catalogo/Botas.jpg"
    },
    {
        categoria: "Calzado",
        titulo: "Zapatos Formales",
        precio: 30000,
        info: "Elegancia para ocasiones especiales",
        tamano: "39-45",
        colores: "Negro",
        marca: "UrbanStep",
        tienda: "Zapatos CR",
        stock: 6,
        fecha: "04-02-2026",
        valoracion: 5,
        imagen: "/img/Catalogo/Zapatos.jpg"
    },
    /* Belleza */
    {
        categoria: "Belleza",
        titulo: "Set Maquillaje Pro",
        precio: 15000,
        info: "Kit completo de maquillaje profesional",
        tamano: "Único",
        colores: "Multicolor",
        marca: "BeautyPro",
        tienda: "Belleza CR",
        stock: 12,
        fecha: "02-01-2026",
        valoracion: 4,
        imagen: "/img/Catalogo/maquillaje.jpg"
    },
    {
        categoria: "Belleza",
        titulo: "Paleta de Sombras",
        precio: 13000,
        info: "Colores intensos y duraderos",
        tamano: "Único",
        colores: "Multicolor",
        marca: "BeautyPro",
        tienda: "Belleza CR",
        stock: 10,
        fecha: "04-01-2026",
        valoracion: 4,
        imagen: "/img/Catalogo/Paleta.jpg"
    },
    {
        categoria: "Belleza",
        titulo: "Secadora de Cabello",
        precio: 22000,
        info: "Secadora potente con múltiples velocidades",
        tamano: "Único",
        colores: "Negro",
        marca: "HairStyle",
        tienda: "Ellas CR",
        stock: 9,
        fecha: "03-03-2026",
        valoracion: 5,
        imagen: "/img/Catalogo/Secadora.jpg"
    },
    {
        categoria: "Belleza",
        titulo: "Plancha de Cabello",
        precio: 25000,
        info: "Alisado profesional rápido",
        tamano: "Único",
        colores: "Negro",
        marca: "HairStyle",
        tienda: "Ellas CR",
        stock: 8,
        fecha: "29-03-2026",
        valoracion: 5,
        imagen: "/img/Catalogo/Plancha.jpg"
    },
    /* Salud */
    {
        categoria: "Salud",
        titulo: "Vitaminas Multivitamínicas",
        precio: 8000,
        info: "Suplemento para energía diaria",
        tamano: "30 cápsulas",
        colores: "N/A",
        marca: "HealthPlus",
        tienda: "Salud CR",
        stock: 25,
        fecha: "25-01-2026",
        valoracion: 4,
        imagen: "/img/Catalogo/vitaminas.jpg"
    },
    {
        categoria: "Salud",
        titulo: "Proteína en Polvo",
        precio: 18000,
        info: "Ideal para recuperación muscular",
        tamano: "1kg",
        colores: "N/A",
        marca: "HealthPlus",
        tienda: "Salud CR",
        stock: 20,
        fecha: "30-03-2026",
        valoracion: 4,
        imagen: "/img/Catalogo/Proteina.png"
    },
    {
        categoria: "Salud",
        titulo: "Termómetro Digital",
        precio: 6000,
        info: "Medición rápida y precisa",
        tamano: "Único",
        colores: "Blanco",
        marca: "MediTech",
        tienda: "Farmacia CR",
        stock: 14,
        fecha: "18-02-2026",
        valoracion: 5,
        imagen: "/img/Catalogo/Termometro.jpg"
    },
    {
        categoria: "Salud",
        titulo: "Oxímetro Digital",
        precio: 9000,
        info: "Mide oxígeno en sangre",
        tamano: "Único",
        colores: "Blanco",
        marca: "MediTech",
        tienda: "Farmacia CR",
        stock: 11,
        fecha: "04-04-2026",
        valoracion: 5,
        imagen: "/img/Catalogo/Oximetro.jpg"
    },
    /* Hogar */
    {
        categoria: "Hogar",
        titulo: "Lámpara LED",
        precio: 9000,
        info: "Iluminación moderna y eficiente",
        tamano: "Único",
        colores: "Blanco, Negro",
        marca: "HomeLight",
        tienda: "Hogar CR",
        stock: 11,
        fecha: "12-03-2026",
        valoracion: 4,
        imagen: "/img/Catalogo/lampara.jpg"
    },
    {
        categoria: "Hogar",
        titulo: "Ventilador Portátil",
        precio: 12000,
        info: "Ideal para espacios pequeños",
        tamano: "Único",
        colores: "Blanco",
        marca: "HomeLight",
        tienda: "Hogar CR",
        stock: 10,
        fecha: "04-02-2026",
        valoracion: 4,
        imagen: "/img/Catalogo/Ventilador.jpg"
    },
    {
        categoria: "Hogar",
        titulo: "Juego de Sábanas",
        precio: 14000,
        info: "Sábanas suaves y resistentes",
        tamano: "Queen",
        colores: "Blanco, Gris",
        marca: "ComfortHome",
        tienda: "Mundo CR",
        stock: 7,
        fecha: "30-01-2026",
        valoracion: 5,
        imagen: "/img/Catalogo/Sabanas.jpg"
    },
    {
        categoria: "Hogar",
        titulo: "Cobija Térmica",
        precio: 16000,
        info: "Abrigo suave para noches frías",
        tamano: "Queen",
        colores: "Gris, Beige",
        marca: "ComfortHome",
        tienda: "Mundo CR",
        stock: 6,
        fecha: "31-03-2026",
        valoracion: 5,
        imagen: "/img/Catalogo/Cobija.jpg"
    },
    /* Tecnología */
    {
        categoria: "Tecnología",
        titulo: "Audífonos Bluetooth",
        precio: 18000,
        info: "Sonido de alta calidad inalámbrico",
        tamano: "Único",
        colores: "Negro",
        marca: "SoundMax",
        tienda: "Tech CR",
        stock: 16,
        fecha: "03-01-2026",
        valoracion: 5,
        imagen: "/img/Catalogo/audifonos.jpg"
    },
    {
        categoria: "Tecnología",
        titulo: "Parlante Bluetooth",
        precio: 22000,
        info: "Sonido potente portátil",
        tamano: "Único",
        colores: "Negro",
        marca: "SoundMax",
        tienda: "Tech CR",
        stock: 14,
        fecha: "04-03-2026",
        valoracion: 4,
        imagen: "/img/Catalogo/Parlante.jpg"
    },
    {
        categoria: "Tecnología",
        titulo: "Smartwatch",
        precio: 35000,
        info: "Reloj inteligente con múltiples funciones",
        tamano: "Único",
        colores: "Negro, Gris",
        marca: "TechWear",
        tienda: "Mente CR",
        stock: 6,
        fecha: "10-03-2026",
        valoracion: 4,
        imagen: "/img/Catalogo/Smartwatch.jpg"
    },
    {
        categoria: "Tecnología",
        titulo: "Pulsera Inteligente",
        precio: 27000,
        info: "Monitoreo de salud y actividad",
        tamano: "Único",
        colores: "Negro, Azul",
        marca: "TechWear",
        tienda: "Mente CR",
        stock: 7,
        fecha: "05-04-2026",
        valoracion: 5,
        imagen: "/img/Catalogo/Pulsera.jpeg"
    },
    /* Niños */
    {
        categoria: "Niños",
        titulo: "Juguete Educativo",
        precio: 7000,
        info: "Juego didáctico para aprendizaje",
        tamano: "Único",
        colores: "Multicolor",
        marca: "EduKids",
        tienda: "Niños CR",
        stock: 18,
        fecha: "15-01-2026",
        valoracion: 5,
        imagen: "/img/Catalogo/juguete.jpg"
    },
    {
        categoria: "Niños",
        titulo: "Rompecabezas Educativo",
        precio: 8000,
        info: "Estimula la mente y creatividad",
        tamano: "Único",
        colores: "Multicolor",
        marca: "EduKids",
        tienda: "Niños CR",
        stock: 15,
        fecha: "04-01-2026",
        valoracion: 5,
        imagen: "/img/Catalogo/Rompecabezas.jpg"
    },
    {
        categoria: "Niños",
        titulo: "Mochila Escolar",
        precio: 11000,
        info: "Mochila resistente y colorida",
        tamano: "Único",
        colores: "Rojo, Azul",
        marca: "SchoolPack",
        tienda: "Niños CR",
        stock: 13,
        fecha: "22-02-2026",
        valoracion: 4,
        imagen: "/img/Catalogo/Mochila.jpg"
    },
    {
        categoria: "Niños",
        titulo: "Lonchera Escolar",
        precio: 9000,
        info: "Ideal para llevar alimentos",
        tamano: "Único",
        colores: "Azul, Rojo",
        marca: "SchoolPack",
        tienda: "Niños CR",
        stock: 12,
        fecha: "04-04-2026",
        valoracion: 4,
        imagen: "/img/Catalogo/Lonchera.jpg"
    }
];